server:
  port: 8888

encrypt:
  key: Spring_Cloud_Config_server

spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rdessai18/ConfigServerRepository
          username: rdessai18
          password: "{cipher}34695c008ce52d41a94cb13fe9dd3ac2c6747df08739222bc5e7da962906cd7085eb59a6b32dde14f83a18f5996e3316af5e1e74efe2d476f416c7a29564e233"
          clone-on-start: true
          default-label: main
          search-paths:
            - EventDrivenKafka/
            - ScalerProject/
logging:
  level:
    root: trace
    org.spring.framework.cloud.config: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true