server:
  port: 8888

spring:
  application:
    name: ConfigServer
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: classpath:/config-repository
        bootstrap: true

logging:
  level:
    root: trace
    org.spring.framework.cloud.config: debug
